### ISSUE TITLE
doorkeeper 4.0.0 & grape-doorkeeper 0.0.2 support (for runtime dependency)

### ISSUE THREAD

**Issue by tabish-saleem-nxb** [fuCtor/grape-doorkeeper#17]
Hi,
I am facing below issue while trying to upgrade doorkeeper version from 1.4.0 to 4.0.0 in gemspec file (i.e runtime dependency):
grape-doorkeeper (> 0.0.2) was resolved to 0.0.2, which depends on
doorkeeper (> 1.4.0)

Can anyone help me please how can I upgrade doorkeeper version with grape-doorkeeper?

**Comment by fuCtor** [comment]
This gem is outdated and last version of grape has native support.
Try this https://github.com/doorkeeper-gem/doorkeeper/wiki/Grape-integration
